<div class="sidebar">
    <div class="sidebar-head sidebar-head-hidden">
    <?php if($session->user->id != null && $session->user->id != ''): ?>
        <div class="username"><?php echo $session->user->email ?></div>
        <div class="user-option">Update Preferences</div>
        <div class="user-option">Sign Out</div>
    <?php endif ?>
    </div><!-- /.sidebar-head -->
    <div class="list-group">
        <?php foreach($categories as $category): ?>
            <a class="list-group-item"><?php echo $category->name ?></a>
        <?php endforeach ?>
    </div><!-- /.list-group -->
</div><!-- /.sidebar -->