<div class="sidebar">
    <div class="sidebar-head sidebar-head-hidden">
        <div class="username">Username</div>
        <div class="user-option">Update Preferences</div>
        <div class="user-option">Sign Out</div>
    </div><!-- /.sidebar-head -->
    <div class="list-group">
        <?php foreach($categories as $category): ?>
            <a class="list-group-item"><?php echo $category->name ?></a>
        <?php endforeach ?>
    </div><!-- /.list-group -->
</div><!-- /.sidebar -->