<div class="sidebar">
    <div class="sidebar-head sidebar-head-hidden">
    <?php if(isset($session->user->id)): ?>
        <div class="username"><?php echo $session->user->email ?></div>
        <a class="user-option" href="<?php echo $this->url('home') ?>">Update Preferences</a>
        <a class="user-option" href="<?php echo $this->url('signout') ?>">Sign Out</a>
    <?php else: ?>
        <a class="user-option" href="<?php echo $this->url('home') ?>">Sign In</a>
    <?php endif ?>
    </div><!-- /.sidebar-head -->
    <div class="list-group">
        <?php foreach($categories as $category): ?>
            <a class="list-group-item"><?php echo $category->name ?></a>
        <?php endforeach ?>
    </div><!-- /.list-group -->
</div><!-- /.sidebar -->