<div class="container-fluid no-padding offset-nav">
    <div class="page-header">
        <h1>Vote Submission</h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <div class="well text-center">
                <p><?php echo $message ?></p>
            </div><!-- /.well -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.container-fluid -->