<div class="container-fluid no-padding offset-nav">
    <div class="page-header">
        <h1>Vote Submission</h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-sm-4">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Banner 1 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-4148229118175472"
                 data-ad-slot="4299823747"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div><!-- /.col -->
        <div class="col-sm-4">
            <div class="well text-center">
                <p><?php echo $message ?></p>
            </div><!-- /.well -->
        </div><!-- /.col -->
        <div class="col-sm-4">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Banner 1 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-4148229118175472"
                 data-ad-slot="4299823747"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.container-fluid -->