<div class="container offset-nav">
    <div class="page-header">
        <h1>Manage Jokes</h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-sm-6">
            <div class="panel">
                <form id="add-joke-form">
                    <div class="panel-heading">
                        <h2>Add New Jokes</h2>
                    </div><!-- /.panel-footer -->
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="joke">Joke</label>
                            <textarea class="form-control" name="joke" id="joke" value="" placeholder="Joke"></textarea>
                        </div><!-- /.form-group -->
                        <div class="form-group">
                            <label for="answer">Answer (optional)</label>
                            <textarea class="form-control" name="answer" id="answer" value="" placeholder="Answer"></textarea>
                        </div><!-- /.form-group -->
                        <div class="form-group">
                            <table class="checkbox-tile-table">
                                <?php $i = 0 ?>
                                <?php foreach($categories as $category): ?>
                                    <?php if ($i % 4 === 0): ?>
                                        <?php if ($i !== 0): ?>
                                            </tr>
                                        <?php endif; ?>
                                        <tr class="checkbox-tile-row">
                                    <?php endif; ?>
                                        <td class="checkbox-tile">
                                            <span class="checkbox-tile-label"><?php echo $category->name ?></span>
                                            <div class="checkbox-tile-hidden">
                                                <input type="checkbox" class="add-category" name="category[<?php echo $category->name ?>]" value="<?php echo $category->cat_id ?>">
                                            </div><!-- /.checkbox-tile-hidden -->
                                        </td><!--  /.checkbox-tile -->
                                    <?php $i++ ?>
                                <?php endforeach; ?>
                                </tr>
                            </table>
                        </div><!-- /.form-group -->
                    </div><!-- /.panel-body -->
                    <div class="panel-footer text-right">
                        <button type="submit" name="submit" class="btn btn-success">Add Joke</button>
                    </div><!-- /.panel-footer -->
                </form>
            </div><!-- /.panel -->
        </div><!-- /.col -->
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <form id="remove-joke-form">
                            <div class="panel-heading">
                                <h2>Remove A Joke</h2>
                            </div><!-- /.panel-heading -->
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="joke_id">Joke ID</label>
                                    <input type="text" class="form-control" name="joke_id" id="joke_id" value="" placeholder="Joke ID">
                                </div><!-- /.form-group -->
                            </div><!-- /.panel-body -->
                            <div class="panel-footer text-right">
                                <button type="submit" name="submit" class="btn btn-danger">Remove Joke</button>
                            </div><!-- /.panel-footer -->
                        </form>
                    </div><!-- /.panel -->
                </div><!-- /.col -->
            </div><!-- /.row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel" id="update-jokes-well" <?php if($jokeCategories): ?>style="display:none"<?php endif ?>>
                        <form id="get-joke-categories-form">
                            <div class="panel-heading">
                                <h2>Update a Joke's Categories</h2>
                            </div><!-- /.panel-heading -->
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="joke_id2">Joke ID</label>
                                    <input type="text" class="form-control" name="joke_id" id="joke_id2" value="" placeholder="<?php echo ($message) ? $message : 'Joke ID' ?>">
                                </div><!-- /.form-group -->
                            </div><!-- /.panel-body -->
                            <div class="panel-footer text-right">
                                <button type="submit" name="submit" class="btn btn-primary">Get Joke Categories</button>
                            </div><!-- /.panel-footer -->
                        </form>
                    </div><!-- /.panel -->
                    <div class="panel" id="update-jokes-categories-well" <?php if(!$jokeCategories): ?>style="display:none"<?php endif ?>>
                        <form id="update-joke-categories-form">
                            <div class="panel-heading">
                                <h2>Update a Joke's Categories</h2>
                            </div><!-- /.panel-heading -->
                            <div class="panel-body">
                                <?php if($joke): ?>
                                    <p><?php echo $joke->joke ?></p>
                                <?php else: ?>
                                    <p><?php echo $message ?>
                                <?php endif ?>
                                <?php if($joke && isset($joke->answer)): ?>
                                    <p><?php echo $joke->answer ?></p>
                                <?php endif ?>
                                <input type="hidden" name="hidden_joke_id" id="hidden_joke_id" value="<?php echo ($joke) ? $joke->joke_id : '' ?>">
                                <?php if ($joke): ?>
                                    <div class="form-group">
                                        <table class="checkbox-tile-table">
                                            <?php $i = 0 ?>
                                            <?php foreach($categories as $category): ?>
                                                <?php $match = false ?>
                                                <?php if($jokeCategories): ?>
                                                    <?php foreach($jokeCategories as $jokeCategory): ?>
                                                        <?php if($jokeCategory->cat_id == $category->cat_id):?>
                                                            <?php $match = true ?>
                                                            <?php continue ?>
                                                        <?php endif ?>
                                                    <?php endforeach ?>
                                                <?php endif ?>
                                                <?php if ($i % 4 === 0): ?>
                                                    <?php if ($i !== 0): ?>
                                                        </tr>
                                                    <?php endif; ?>
                                                    <tr class="checkbox-tile-row">
                                                <?php endif; ?>
                                                    <td class="checkbox-tile <?php echo ($match) ? 'checked' : '' ?>">
                                                        <span class="checkbox-tile-label"><?php echo $category->name ?></span>
                                                        <div class="checkbox-tile-hidden">
                                                            <input type="checkbox" class="add-category" name="category[<?php echo $category->name ?>]" <?php echo ($match) ? 'checked="true"' : '' ?> value="<?php echo $category->cat_id ?>">
                                                        </div><!-- /.checkbox-tile-hidden -->
                                                    </td><!--  /.checkbox-tile -->
                                                <?php $i++ ?>
                                            <?php endforeach; ?>
                                            </tr>
                                        </table>
                                    </div><!-- /.form-group -->
                                <?php endif ?>
                            </div><!-- /.panel-body -->
                            <div class="panel-footer text-right">
                                <button type="button" id="update-jc-back-btn" class="btn btn-danger">Back</button>
                                <button type="submit" name="submit" class="btn btn-success">Update Joke Categories</button>
                            </div><!-- /.panel-footer -->
                        </form>
                    </div><!-- /.panel -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.container -->