<div class="container-fluid no-padding">
    <?php if($catflag && $message != "Success"): ?>
        <div class="row">
            <div class="col-sm-12">
                <div class="well">
                    <p><?php echo $message ?></p>
                </div><!-- /.well -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    <?php else: ?>
        <div class="page-header">
                <h1>Jokes<br/><small><?php echo ($categoryObject) ? $categoryObject->name : "All Jokes" ?></small></h1>
        </div><!-- /.page-header -->
        <?php $total = count($jokes) ?>
        <div class="row masonry <?php if($total == 1): ?>max-500<?php elseif($total == 2): ?>max-783<?php elseif($total == 3): ?>max-1049<?php elseif($total == 4):?>max-1315<?php endif ?>">
            <?php foreach($jokes as $joke): ?>
                <?php /*-- get total vote count for current joke --*/ ?>
                <?php $voteCount = 0 ?>
                <?php foreach($votes as $vote): ?>
                    <?php if($vote->joke_id == $joke->joke_id): ?>
                        <?php $voteCount += (int) $vote->vote //sum of all votes for this joke ?>
                    <?php endif ?>
                <?php endforeach ?>
                <?php /*-- show if user has upvoted/downvoted with colored thumbs --*/ ?>
                <?php $thumbsUp = 'fa-thumbs-o-up' //user has not voted ?>
                <?php $thumbsDown = 'fa-thumbs-o-down' ?>
                <?php $session->userVotes = (isset($session->userVotes)) ? $session->userVotes : array(); ?>
                <?php foreach($session->userVotes as $userVote): ?>
                    <?php if($userVote->joke_id == $joke->joke_id): ?>
                        <?php if($userVote->vote == 1): ?>
                            <?php $thumbsUp = 'fa-thumbs-up' //user has upvoted this already ?>
                            <?php $thumbsDown = 'fa-thumbs-o-down' ?>
                        <?php elseif($userVote->vote == -1): ?>
                            <?php $thumbsUp = 'fa-thumbs-o-up' //user has downvoted this already ?>
                            <?php $thumbsDown = 'fa-thumbs-down' ?>
                        <?php else: ?>
                        <? endif ?>
                    <?php endif ?>
                <?php endforeach ?>
                <div class="item">
                    <div class="panel" id="<?php echo $joke->joke_id ?>">
                        <div class="panel-body">
                            <p class="joke"><?php echo $joke->joke ?></p>
                            <?php if ($joke->answer): ?>
                                <p class="joke-answer"><?php echo $joke->answer ?></p>
                            <?php endif ?>
                        </div><!-- /.panel-body -->
                        <div class="panel-footer">
                            <i class="fa fa-tags categories" data-toggle="popover" title="Categories" data-content="
                                <?php $i = 0 ?>
                                <?php foreach($jokeCategories as $jokeCategory): ?>
                                    <?php if($jokeCategory->joke_id == $joke->joke_id): ?>
                                        <?php if($i > 0): ?>
                                            <?php echo " | " . $jokeCategory->name ?>
                                        <?php else: ?>
                                            <?php echo $jokeCategory->name ?>
                                        <?php endif ?>
                                        <?php $i++ ?>
                                    <?php endif ?>
                                <?php endforeach ?>
                            " data-trigger="hover focus"></i>
                            <span class="pull-right">
                                <span class="vote-count"><?php echo $voteCount ?></span>
                                <i class="fa <?php echo $thumbsUp ?> vote up-vote"></i>
                                <i class="fa <?php echo $thumbsDown ?> vote down-vote"></i>
                            </span>
                        </div><!-- /.panel-footer -->
                    </div><!-- /.panel -->
                </div><!-- /.item -->
            <?php endforeach ?>
        </div><!-- /.row -->

        <div class="page-footer">
            <nav>
                <ul class="pagination pagination-md">
                    <li <?php if($page == 1): ?>class="disabled"<?php endif ?>>
                        <a aria-label="Previous" href="<?php echo ($page == 1) ? '#' : strtok($_SERVER["REQUEST_URI"], '?') . '?page=' . ((int) $page - 1) ?>"><span aria-hidden="true">«</span></a>
                    </li>
                    <?php for($i = 1; $i <= $maxPages; $i++): ?>
                        <?php if ($i > ($page - 5) && $i < ($page + 5)): ?>
                            <li <?php if($page == $i): ?>class="active"<?php endif ?>>
                                <a href="<?php echo strtok($_SERVER["REQUEST_URI"], '?') . '?page=' . $i ?>"><?php echo $i ?><span class="sr-only">(current)</span></a>
                            </li>
                        <?php endif ?>
                    <?php endfor ?>
                    <li <?php if($page == $maxPages): ?>class="disabled"<?php endif ?>>
                        <a aria-label="Next" href="<?php echo ($page == $maxPages) ? '#' : strtok($_SERVER["REQUEST_URI"], '?') . '?page=' . ((int) $page + 1) ?>"><span aria-hidden="true">»</span></a>
                    </li>
                </ul>
            </nav>
        </div><!-- /.page-footer -->
    <?php endif ?>
</div><!-- /.contianer -->