<div class="container-fluid no-padding">
    <div class="page-header">
        <div class="container">
            <h1>Jokes <small>All Jokes</small></h1>
        </div><!-- /.container -->
    </div><!-- /.page-header -->
    <div class="row masonry">
        <?php foreach($jokes as $joke): ?>
            <?php /*-- get total vote count for current joke --*/ ?>
            <?php $voteCount = 0 ?>
            <?php foreach($votes as $vote): ?>
                <?php if($vote->joke_id == $joke->joke_id): ?>
                    <?php $voteCount += (int) $vote->vote //sum of all votes for this joke ?>
                <?php endif ?>
            <?php endforeach ?>
            <?php /*-- show if user has upvoted/downvoted with colored thumbs --*/ ?>
            <?php $thumbsUp = 'fa-thumbs-o-up' //user has not voted ?>
            <?php $thumbsDown = 'fa-thumbs-o-down' ?>
            <?php $session->userVotes = (isset($session->userVotes)) ? $session->userVotes : array(); ?>
            <?php foreach($session->userVotes as $userVote): ?>
                <?php if($userVote->joke_id == $joke->joke_id): ?>
                    <?php if($userVote->vote == 1): ?>
                        <?php $thumbsUp = 'fa-thumbs-up' //user has upvoted this already ?>
                        <?php $thumbsDown = 'fa-thumbs-o-down' ?>
                    <?php elseif($userVote->vote == -1): ?>
                        <?php $thumbsUp = 'fa-thumbs-o-up' //user has downvoted this already ?>
                        <?php $thumbsDown = 'fa-thumbs-down' ?>
                    <?php else: ?>
                    <? endif ?>
                <?php endif ?>
            <?php endforeach ?>
            <div class="item">
                <div class="panel" id="<?php echo $joke->joke_id ?>">
                    <div class="panel-body">
                        <p class="joke"><?php echo $joke->joke ?></p>
                        <?php if ($joke->answer): ?>
                            <p class="joke-answer"><?php echo $joke->answer ?></p>
                        <?php endif ?>
                    </div><!-- /.panel-body -->
                    <div class="panel-footer">
                        <i class="fa fa-tags categories" data-toggle="popover" title="Categories" data-content="
                            <?php $i = 0 ?>
                            <?php foreach($jokeCategories as $jokeCategory): ?>
                                <?php if($jokeCategory->joke_id == $joke->joke_id): ?>
                                    <?php if($i > 0): ?>
                                        <?php echo " | " . $jokeCategory->name ?>
                                    <?php else: ?>
                                        <?php echo $jokeCategory->name ?>
                                    <?php endif ?>
                                    <?php $i++ ?>
                                <?php endif ?>
                            <?php endforeach ?>
                        " data-trigger="hover focus"></i>
                        <span class="pull-right">
                            <span class="vote-count"><?php echo $voteCount ?></span>
                            <i class="fa <?php echo $thumbsUp ?> vote up-vote"></i>
                            <i class="fa <?php echo $thumbsDown ?> vote down-vote"></i>
                        </span>
                    </div><!-- /.panel-footer -->
                </div><!-- /.panel -->
            </div><!-- /.item -->
        <?php endforeach ?>
    </div><!-- /.row -->

    <div class="page-footer">
        <nav>
            <ul class="pagination pagination-md">
                <li class="disabled">
                    <a aria-label="Previous" href="#"><span aria-hidden="true">«</span></a>
                </li>
                <li class="active">
                    <a href="#">1<span class="sr-only">(current)</span></a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a aria-label="Next" href="#"><span aria-hidden="true">»</span></a>
                </li>
            </ul>
        </nav>
    </div><!-- /.page-footer -->
</div><!-- /.contianer -->