<div class="container-fluid no-padding offset-nav">
    <div class="page-header">
        <h1>Jokes
            <?php if(!$jokeflag): ?>
                <br/>
                <small>
                    <?php if($searchflag): ?>
                        <?php echo 'Seach results for "<span class="highlight">' . $search . '</span>"'?>
                    <?php elseif($categoryObject): ?>
                        <?php echo $categoryObject->name ?>
                    <?php else: ?>
                        <?php echo "All Jokes" ?>
                    <?php endif ?>
                </small>
            <?php endif ?>
        </h1>
    </div><!-- /.page-header -->
    <?php if(($catflag || $searchflag) && $message != "Success"): ?>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="well">
                        <p><?php echo $message ?></p>
                    </div><!-- /.well -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    <?php else: ?>
        <div class="row masonry <?php if($totalOnPage < 6):?>less-than-six<?php endif ?> col-<?php echo $totalOnPage ?>">
            <?php foreach($jokes as $joke): ?>
                <?php $joke->joke = trim(preg_replace('/[\r|\n]+/', '<br>', $joke->joke)) //replace newlines with HTML breaks ?>
                <?php /*-- get total vote count for current joke --*/ ?>
                <?php $voteCount = 0 ?>
                <?php foreach($votes as $vote): ?>
                    <?php if($vote->joke_id == $joke->joke_id): ?>
                        <?php $voteCount += (int) $vote->vote //sum of all votes for this joke ?>
                    <?php endif ?>
                <?php endforeach ?>
                <?php /*-- show if user has upvoted/downvoted with colored thumbs --*/ ?>
                <?php $thumbsUp = 'fa-thumbs-o-up' //user has not voted ?>
                <?php $thumbsDown = 'fa-thumbs-o-down' ?>
                <?php $session->userVotes = (isset($session->userVotes)) ? $session->userVotes : array(); ?>
                <?php foreach($userVotes as $userVote): ?>
                    <?php if($userVote->joke_id == $joke->joke_id): ?>
                        <?php if($userVote->vote == 1): ?>
                            <?php $thumbsUp = 'fa-thumbs-up' //user has upvoted this already ?>
                            <?php $thumbsDown = 'fa-thumbs-o-down' ?>
                        <?php elseif($userVote->vote == -1): ?>
                            <?php $thumbsUp = 'fa-thumbs-o-up' //user has downvoted this already ?>
                            <?php $thumbsDown = 'fa-thumbs-down' ?>
                        <?php else: ?>
                        <? endif ?>
                    <?php endif ?>
                <?php endforeach ?>
                <div class="item">
                    <div class="panel" id="<?php echo $joke->joke_id ?>">
                        <div class="panel-body no-select">
                            <p class="joke">
                                <?php if($searchflag): ?>
                                    <?php echo str_ireplace($search, '<span class="highlight">' . $search . '</span>', $joke->joke) ?>
                                <?php else: ?>
                                    <?php echo $joke->joke ?>
                                <?php endif ?>
                            </p>
                            <?php if ($joke->answer): ?>
                                <p class="joke-answer text-blurred">
                                    <?php if($searchflag): ?>
                                        <?php echo str_ireplace($search, '<span class="highlight">' . $search . '</span>', $joke->answer) ?>
                                    <?php else: ?>
                                        <?php echo $joke->answer ?>
                                    <?php endif ?>
                                </p>
                            <?php endif ?>
                            <span class="joke-categories">
                                Categories:
                                <span class="dark-secondary">
                                    <?php $i = 0 ?>
                                    <?php foreach($jokeCategories as $jokeCategory): ?>
                                        <?php if($jokeCategory->joke_id == $joke->joke_id): ?>
                                            <?php $link = '<a href="' . $this->url('joke', array('action' => 'view', 'category' => $catArray[$jokeCategory->cat_id])) . '">' . $jokeCategory->name . '</a>' ?>
                                                <?php echo ($i > 0) ? " | " . $link : $link ?>
                                            <?php $i++ ?>
                                        <?php endif ?>
                                    <?php endforeach ?>
                                </span>
                            </span>
                        </div><!-- /.panel-body -->
                        <div class="panel-footer no-select">
                            <?php
                                $joke->joke = trim(preg_replace('/[\r|\n|\r\n]+/', '%0A', $joke->joke));
                                $joke->joke = preg_replace('/"/', '%22', $joke->joke);
                                $joke->answer = trim(preg_replace('/[\r|\n|\r\n]+/', '%0A', $joke->answer));
                                $joke->answer = preg_replace('/"/', '%22', $joke->answer);
                                $emailSubject = '?subject=Check out this joke from SendMeJokes!';
                                $emailBody = '&amp;body=' . $joke->joke . '%0A';
                                $emailBody .= trim(preg_replace('/\s+/', ' ', $joke->answer)) . '%0A%0A';
                                $emailBody .= 'See more at http:%2F%2Fwww.sendmejokes.com/jokes';
                                $email = $emailSubject . $emailBody;
                            ?>
                            <a class="share" href="mailto:<?php echo $email ?>"><i class="fa fa-envelope"></i></a>
                            <a class="share" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A//www.sendmejokes.com/jokes/view/<?php echo $joke->joke_id ?>/"><i class="fa fa-link-out"></i></a><!-- changed name of fb icon to get past addBlock -->
                            <a class="share" target="_blank" href="https://plus.google.com/share?url=http%3A//www.sendmejokes.com/jokes/view/<?php echo $joke->joke_id ?>/"><i class="fa fa-link-out2"></i></a><!-- changed name of g+ icon to get past addBlock -->
                            <a class="share" target="_blank" href="/jokes/view/<?php echo $joke->joke_id ?>/"><i class="fa fa-external-link-square"></i></a>
                            <span class="pull-right">
                                <i class="fa <?php echo $thumbsUp ?> vote up-vote"></i>
                                <span class="vote-count"><?php echo $voteCount ?></span>
                                <i class="fa <?php echo $thumbsDown ?> vote down-vote"></i>
                            </span>
                        </div><!-- /.panel-footer -->
                    </div><!-- /.panel -->
                </div><!-- /.item -->
            <?php endforeach ?>
        </div><!-- /.row -->

        <div class="page-footer">
            <input type="hidden" id="max-pages" value="<?php echo $maxPages ?>">
            <input type="hidden" id="page-number" value="1">
            <span id="joke-loader"></span>
            <?php /* PAGINATION if(!$jokeflag && $maxPages > 1): ?>
                <nav>
                    <ul class="pagination pagination-md">
                        <li <?php if($page == 1): ?>class="disabled"<?php endif ?>>
                            <a aria-label="Previous" class="pagination-link" href="<?php echo ($page == 1) ? '#' : strtok($_SERVER["REQUEST_URI"], '?') . '?page=' . ((int) $page - 1) ?>"><span aria-hidden="true">«</span></a>
                        </li>
                        <?php for($i = 1; $i <= $maxPages; $i++): ?>
                            <?php if ($i > ($page - 5) && $i < ($page + 5)): ?>
                                <li <?php if($page == $i): ?>class="active"<?php endif ?>>
                                    <a class="pagination-link" href="<?php echo strtok($_SERVER["REQUEST_URI"], '?') . '?page=' . $i ?>"><?php echo $i ?><span class="sr-only">(current)</span></a>
                                </li>
                            <?php endif ?>
                        <?php endfor ?>
                        <li <?php if($page == $maxPages): ?>class="disabled"<?php endif ?>>
                            <a aria-label="Next" class="pagination-link" href="<?php echo ($page == $maxPages) ? '#' : strtok($_SERVER["REQUEST_URI"], '?') . '?page=' . ((int) $page + 1) ?>"><span aria-hidden="true">»</span></a>
                        </li>
                    </ul>
                </nav>
            <?php endif */ ?>
        </div><!-- /.page-footer -->
    <?php endif ?>
</div><!-- /.contianer -->