<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SendMeJokes')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/smj.css')
                        ->prependStylesheet($this->basePath() . '/css/smj-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/transformicon.css')
                        ->prependStylesheet($this->basePath() . '/css/animate.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        ?>
    </head>
    <body>
        <div class="sidebar">
            <h3 class="sidebar-head sidebar-head-hidden">BROWSE</h3>
            <div class="list-group">
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
                <a class="list-group-item">Category</a>
            </div><!-- /.list-group -->
        </div><!-- /.sidebar -->
        <div class="full-height container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="logo hidden-xs hidden-sm">
                        <a class="logo-anchor" href="<?php echo $this->url('home') ?>">
                            <img class="logo-img" src="/img/logo-light.png">
                        </a>
                    </div><!-- /.logo -->
                    <div class="browse-button">
                        <button class="c-hamburger c-hamburger--htx">
                            <span>toggle menu</span>
                        </button>
                    </div><!-- /.browse-button -->
                </div><!-- /.col -->
            </div><!-- /.row -->
            <?php echo $this->content ?>
        </div><!-- /.container-fluid -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/smj.js')
                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/jquery.min.js')
                        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
