<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->headTitle('SendMeJokes')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendName('description', 'Sendmejokes - Browse all of our jokes, and sign up to get them emailed to you everyday!')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                        ->setCharset('utf-8')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/smj.css')
                        ->prependStylesheet($this->basePath() . '/css/smj-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/transformicon.css')
                        ->prependStylesheet($this->basePath() . '/css/animate.css')
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        ?>
    </head>
    <body>
        <?php echo $this->sidebar() ?>

        <div class="full-height container-fluid">

            <div class="row">
                <div class="col-sm-12">
                    <a class="logo-anchor" href="<?php echo $this->url('home') ?>">
                        <img class="logo-img" src="/img/logo-light.png">
                    </a>
                    <div class="browse-button">
                        <button class="c-hamburger c-hamburger--htx">
                            <span>toggle menu</span>
                        </button>
                    </div><!-- /.browse-button -->
                </div><!-- /.col -->
            </div><!-- /.row -->

            <?php echo $this->content ?>

            <form id="signin-form">
                <div id="signin-modal" class="modal fade">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Sign In</h4>
                            </div><!-- /.modal-header -->
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="email">Email:</label>
                                    <input id="email" class="form-control" type="text" value="" name="email">
                                </div><!-- /.form-group -->
                                <div class="form-group">
                                    <label for="password">Password:</label>
                                    <input id="password" class="form-control" type="password" value="" name="password">
                                </div><!-- /.form-group -->
                                <a class="forgot-password-link" href="#">forgot password?</a>
                                <div class="modal-alert">text</div>
                            </div><!-- /.modal-body -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                <button name="submit" type="submit" value="submit" class="btn btn-primary">Sign In</button>
                            </div><!-- /.modal-footer -->
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
            </form>

        </div><!-- /.container-fluid -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/smj.js')
                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/jquery.min.js')
                        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
