<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->headTitle('SendMeJokes')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
                        ->setProperty('og:url',         'http://www.sendmejokes.com/')
                        ->setProperty('og:type',        'website')
                        ->setProperty('og:title',       'SendMeJokes')
                        ->setProperty('og:description', 'Jokes sent to you daily')
                        ->setProperty('og:image',       'http://www.sendmejokes.com/img/logo-light.png')
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendName('description', 'Sendmejokes - Browse all of our jokes, and sign up to get them emailed to you everyday!')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                        ->setCharset('utf-8')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/smj.css')
                        ->prependStylesheet($this->basePath() . '/css/smj-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/transformicon.css')
                        ->prependStylesheet($this->basePath() . '/css/animate.css')
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        ?>
    </head>
    <body>        
        <?php echo $this->sidebar() ?>
        
        <a class="logo-anchor" href="<?php echo $this->url('home') ?>">
            <img class="logo-img" src="/img/logo-light.png">
        </a>

        <div class="browse-button">
            <button class="c-hamburger c-hamburger--htx">
                <span>toggle menu</span>
            </button>
        </div><!-- /.browse-button -->

        <div class="main full-height container-fluid">

            <?php echo $this->content ?>

            <form id="signin-form">
                <div id="signin-modal" class="modal fade">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Sign In</h4>
                            </div><!-- /.modal-header -->
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="email">Email:</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></div>
                                        <input id="email" class="form-control" type="text" value="" name="email" placeholder="Email">
                                    </div>
                                </div><!-- /.form-group -->
                                <div class="form-group" id="signin-form-password">
                                    <label for="password">Password:</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-key fa-fw"></i></div>
                                    <input id="password" class="form-control" type="password" value="" name="password" placeholder="Password">
                                    </div>
                                </div><!-- /.form-group -->
                                <a class="forgot-password-link" href="#">Forgot password?</a>
                                <a class="need-account-link" href="<?php echo $this->url('home') ?>">Create an account</a>
                                <div class="modal-alert">text</div>
                            </div><!-- /.modal-body -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                <button name="submit" type="submit" value="submit" id="signin-form-submit" class="btn btn-primary">Sign In</button>
                            </div><!-- /.modal-footer -->
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
            </form>
            
            <div id="alert-modal" class="modal fade">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">title</h4>
                        </div><!-- /.modal-header -->
                        <div class="modal-body">
                            body
                        </div><!-- /.modal-body -->
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

            <?php //echo $this->updatePreferencesModal(); ?>
        </div><!-- /.container-fluid -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/smj.js')
                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/jquery.min.js')
                        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
