<?php if($message == 'get-form'): ?>
    <div class="home middle-align-out">
        <div class="middle-align-in">
            <h1 class="light">Ahh so you forgot your password...</h1>
            <form id="reset-password-form">
                <input type="hidden" name="id" value="<?php echo $id ?>">
                <div class="form-group">
                    <label for="email" class="light">Enter your email address</label>
                    <input type="text" class="form-control" name="email" id="email" value="">
                </div><!-- /.form-group -->
                <div class="form-group">
                    <label for="password1" class="light">Enter a new password</label>
                    <input type="password" class="form-control" name="password1" id="password1" value="">
                </div><!-- /.form-group -->
                <div class="form-group">
                    <label for="password2" class="light">Enter your new password again</label>
                    <input type="password" class="form-control" name="password2" id="password2" value="">
                </div><!-- /.form-group -->
                <div class="form-group">
                    <button type="submit" name="submit" class="btn btn-primary">Reset Password</button>
                </div><!-- /.form-group -->
            </form>
        </div><!-- /.middle-align-in -->
    </div><!-- /.middle-align-out -->
<?php else: ?>
    <div class="home middle-align-out">
        <div class="middle-align-in">
            <h1 class="light">Hmm...</h1>
        </div><!-- /.middle-align-in -->
    </div><!-- /.middle-align-out -->
<?php endif ?>