<div class="container offset-nav">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-header">
                <h1>Privacy Policy</h1>
            </div><!-- /.page-header -->
            <div class="well">
                <p class="text-center">Updated: 11/02/2015</p>

                <h2>Information We Collect</h2>
                <p>We do not collect any personal information unless a SendMeJokes User Account is created. In this case, we will collect your email address data.</p>

                <h2>SendMeJokes User Account</h2>
                <p>In order to create a SendMeJokes User Account, you must enter your email address. We will save this email address until you delete your account. We will never sell or give out your email address, or any other information associated with your SendMeJokes User Account. We collect this information in order to deliver emails containing jokes, announcements, or SendMeJokes User Account actions (including but not limited to resetting passwords, removal of account notice, etc.). If you would like to unsubscribe from recieving emails, delete your user account, or have any questions, please send an email to <a href="mailto:mike@sendmejokes.com">mike@sendmejokes.com</a>.</p>

                <h2>Third Party Advertising</h2>
                <p>Www.sendmejokes.com uses third-party advertising companies to serve ads when you visit this Web site. These companies may use information (not including your name, address, email address or telephone number) about your visits to this and other Web sites in order to provide advertisements on this site and other sites about goods and services that may be of interest to you.</p>
                <p>Third party vendors, including Google, use cookies to serve ads based on a user's prior visits to your website.</p>
                <p>Google's use of the DoubleClick cookie enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.</p>
                <p>Users may opt out of the use of the DoubleClick cookie for interest-based advertising by visiting <a href="http://www.google.com/ads/preferences/">Ads Settings</a>.</p>
                <p>To learn more about internet-based advertising and opting out of third-party vendor's use of cookies visit <a href="http://www.aboutads.info/">aboutads.info</a>.</p>

                <h2>Changes to Privacy Policy</h2>
                <p>As our organization, membership, and services evolve, this Privacy Policy may be revised to reflect those changes. We reserve the right to amend this Privacy Policy at any time, for any reason. Notice of such amendments will be posted as an updated Privacy Policy on this website, and an effective date will be indicated. Users are encouraged to check our site frequently to review the current Privacy Policy in effect.</p>
            </div><!-- /.well -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.container -->