<div class="sidebar">
    <div class="sidebar-head-ex">
        <div class="sidebar-head sidebar-head-hidden">
        <?php if(isset($session->user->user_id)): ?>
            <?php $parts = explode("@", $session->user->email) ?>
            <?php $username = $parts[0] ?>
            <div class="username"><?php echo $username ?></div>
            <a id="preferences-link" class="user-option" href="<?php echo $this->url('user', array('action' => 'view', 'user_id' => $session->user->user_id)) ?>"><i class="fa fa-cog fa-spin"> </i>My Preferences</a>
            <?php if($session->user->email == 'mrb2590@gmail.com'): ?>
                <a id="add-joke-link" class="user-option" href="<?php echo $this->url('joke', array('action' => 'manage')) ?>"><i class="fa fa-database"></i> Manage Jokes</a>
            <?php endif ?>
            <a id="signout-link" class="user-option" href="#"><i class="fa fa-sign-in"></i> Sign Out</a>
        <?php else: ?>
            <a class="sign-in-link" data-toggle="modal" data-target="#signin-modal" href="#"><i class="fa fa-sign-in"></i> Sign In</a>
        <?php endif ?>
            <form id="search-form" method="GET" action="<?php echo $this->url('search') ?>">
                <div class="form-group">
                    <div class="input-group">
                        <input id="search" class="form-control" type="text" placeholder="Find a joke" name="search" value="">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
                        </span>
                    </div><!-- /.input-group -->
                </div><!-- /.form-group -->
            </form>
        </div><!-- /.sidebar-head -->
    </div><!-- /.sidebar-head-ex -->
    <div class="list-group">
        <a class="list-group-item" href="<?php echo $this->url('joke', array('action' => 'view')) ?>">View All</a>
        <?php foreach($categories as $category): ?>
            <a class="list-group-item" href="<?php echo $this->url('joke', array('action' => 'view', 'category' => $category->url_name)) ?>"><?php echo $category->name ?></a>
        <?php endforeach ?>
    </div><!-- /.list-group -->
</div><!-- /.sidebar -->