<div class="sidebar">
    <div class="sidebar-head sidebar-head-hidden">
    <?php if(isset($session->user->user_id)): ?>
    <?php $parts = explode("@", $session->user->email) ?>
    <?php $username = $parts[0] ?>
        <div class="username"><?php echo $username ?></div>
        <a id="preferences-link" class="user-option" href="#">Update Preferences</a>
        <a id="signout-link" class="user-option" href="#">Sign Out</a>
    <?php else: ?>
        <a class="sign-in-link" data-toggle="modal" data-target="#signin-modal" href="#">Sign In</a>
    <?php endif ?>
    </div><!-- /.sidebar-head -->
    <div class="list-group">
        <a class="list-group-item" href="<?php echo $this->url('home', array('action' => 'jokes')) ?>">View All</a>
        <?php foreach($categories as $category): ?>
            <a class="list-group-item"><?php echo $category->name ?></a>
        <?php endforeach ?>
    </div><!-- /.list-group -->
</div><!-- /.sidebar -->