<div class="home middle-align-out">
    <div class="middle-align-in">
        <h1 class="light">Sign up for a laugh every day!</h1>
        <form id="sign-up-form-email">
            <div class="form-group">
                <label for="email" class="light">Enter your email address</label>
                <input type="text" class="form-control" name="email" id="email" value="">
            </div>
            <div class="form-group">
                <button type="submit" name="submit" id="submitbutton" class="btn btn-default">Send Me Jokes!</button>
            </div>
        </form>
    </div><!-- /.middle-align-in -->
</div><!-- /.middle-align-out -->