<div class="container no-padding">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel-group" id="joke-accordian" role="tablist" aria-multiselectable="true">

                <?php $i = 0 ?>
                <?php foreach($jokes as $joke): ?>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="heading-<?php echo $i ?>">
                            <a role="button" data-toggle="collapse" data-parent="#joke-accordian" href="#collapse-<?php echo $i ?>" aria-expanded="true" aria-controls="collapse-<?php echo $i ?>">
                                <h4 class="panel-title"><?php echo (strlen($joke->joke) > 30) ? substr($joke->joke, 0, 27) . '...' : $joke->joke; ?>
                                    <span class="pull-right">
                                        <?php foreach($jokeCategories as $jokeCategory): ?>
                                            <?php if($jokeCategory->joke_id == $joke->joke_id): ?>
                                                <span class="categoy-name-joke-view"><?php echo $jokeCategory->name ?></span>
                                            <?php endif ?>
                                        <?php endforeach ?>
                                    </span>
                                </h4>
                            </a>
                        </div><!-- /.panel-heading -->
                        <div id="collapse-<?php echo $i ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?php echo $i ?>">
                            <div class="panel-body">
                                <p class="joke"><?php echo $joke->joke ?></p>
                                <?php if ($joke->answer): ?>
                                    <p class="joke-answer"><?php echo $joke->answer ?></p>
                                <?php endif ?>
                            </div><!-- /.panel-body -->
                        </div><!-- /.collapse -->
                    </div><!-- /.panel -->
                    <?php $i++ ?>
                <?php endforeach ?>

            </div><!-- /#joke-accordian -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.contianer -->